# Generated by Django 5.2.7 on 2025-10-30 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_payment_notes_payment_payment_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='purchase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.purchase'),
        ),
    ]
