# Generated by Django 5.2.7 on 2025-11-02 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_purchase_amount_paid_alter_payment_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
