# Generated by Django 5.2.7 on 2025-11-03 05:02

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_purchase_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='opening_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
